[tox]
minversion = 4.0
envlist = py311,pep8
skip_missing_interpreters = true

[testenv]
package = editable
deps = -r{toxinidir}/requirements-dev.txt
commands = pytest {posargs}

[testenv:pep8]
deps =
    flake8>=7.0.0
    doc8>=1.1.0
commands =
    flake8 backend collector correlation_worker enrichment_worker incident_worker parser_worker rca_copilot horizon_plugin/rca_copilot_horizon
    doc8 README.md CONTRIBUTING.rst doc/source releasenotes/source

[testenv:genconfig]
deps = oslo.config>=9.4.0
commands = oslo-config-generator --config-file etc/oslo-config-generator/rca-copilot.conf

[testenv:releasenotes]
deps = reno>=4.1.0
commands = reno report --ignore-cache --output {envtmpdir}/RELEASENOTES.rst

[flake8]
max-line-length = 220
extend-ignore = E203,W503,W391,F401
exclude = .git,.tox,.venv,build,dist,latex,manim_explainer,*.egg-info
